CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(2000),
    project_type VARCHAR(30) NOT NULL,
    custom_type VARCHAR(100),
    objective VARCHAR(2000),
    start_date DATE,
    target_date DATE,
    status VARCHAR(30) NOT NULL,
    priority VARCHAR(30) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_projects_status ON projects (status);

CREATE TABLE project_tags (
    project_id BIGINT NOT NULL REFERENCES projects (id) ON DELETE CASCADE,
    tag VARCHAR(100) NOT NULL
);

CREATE INDEX idx_project_tags_project_id ON project_tags (project_id);
